SOC612: Data Analytics for the Social Sciences
Date: September 8, 2026
Author: Raphi Duerr
Lecture 1: Introduction

Hello World!

This is a Notebook (.ipynb) script. Let's test a few commands to see if everything runs correctly:


In [1]:
print(2 + 8)
print(2 == 8)
print(2 > 8 or 2 < 8)
print(2 > 8 and 2 < 8)
import math
print(math.sqrt(81))

10
False
True
False
9.0


If everything is ok so far, let's do a few more:

In [2]:
import numpy as np

v = np.arange(1, 11)
x = np.arange(91, 101)
w = np.array(["HK", "NT", "KLN"])

print(v.dtype)
print(w.dtype)
print(len(v))
print(np.unique(w))

a = x + v
b = x * v
c = x - v
d = v / 3

data = np.column_stack((a, b, c, d))
print(data)

int64
<U3
10
['HK' 'KLN' 'NT']
[[9.20000000e+01 9.10000000e+01 9.00000000e+01 3.33333333e-01]
 [9.40000000e+01 1.84000000e+02 9.00000000e+01 6.66666667e-01]
 [9.60000000e+01 2.79000000e+02 9.00000000e+01 1.00000000e+00]
 [9.80000000e+01 3.76000000e+02 9.00000000e+01 1.33333333e+00]
 [1.00000000e+02 4.75000000e+02 9.00000000e+01 1.66666667e+00]
 [1.02000000e+02 5.76000000e+02 9.00000000e+01 2.00000000e+00]
 [1.04000000e+02 6.79000000e+02 9.00000000e+01 2.33333333e+00]
 [1.06000000e+02 7.84000000e+02 9.00000000e+01 2.66666667e+00]
 [1.08000000e+02 8.91000000e+02 9.00000000e+01 3.00000000e+00]
 [1.10000000e+02 1.00000000e+03 9.00000000e+01 3.33333333e+00]]


Final test: import pandas (tidyverse equivalent). To install required packages: pip install numpy pandas

In [3]:
import pandas as pd
print("pandas imported successfully (tidyverse equivalent)")

pandas imported successfully (tidyverse equivalent)
